EXPR = ADD-SUB
<ADD-SUB> = MUL-DIV | ADD | SUB
ADD = ADD-SUB <'+'> MUL-DIV
SUB = ADD-SUB <'-'> MUL-DIV
<MUL-DIV> = TERM | MUL | DIV
MUL = MUL-DIV <'*'> TERM
DIV = MUL-DIV <'/'> TERM
<TERM> = OPERAND | L_PAREN ADD-SUB R_PAREN
OPERAND = CONSTANT | VAR
CONSTANT = SPACE* NUMBER SPACE*
VAR = SPACE* VAR-NAME VAR-ID SPACE*

<VAR-NAME> = #'[a-zA-Z]+'
<VAR-ID> = NUMBER
<NUMBER> = #'[0-9]+'
<SPACE> = <#'\s'>
<L_PAREN> = SPACE* <'('> SPACE*
<R_PAREN> = SPACE* <')'> SPACE*