EXPR = OPERATION
<OPERATION> = OPERAND | ADD | SUB | MUL | DIV
ADD = OPERAND <'+'> OPERAND
SUB = OPERAND <'-'> OPERAND
MUL = OPERAND <'*'> OPERAND
DIV = OPERAND <'/'> OPERAND
<OPERAND> = SPACE* NUMBER SPACE* | SPACE* OPERATION SPACE* | SPACE* LEFT_PAREN SPACE* OPERATION SPACE* RIGHT_PAREN* SPACE*
NUMBER = #'[0-9]+'
<LEFT_PAREN> = <"(">
<RIGHT_PAREN> = <")">
<SPACE> = <#'\s'>
